import Header from "./components/themebuilder/01-Header";
import './globals.css';

export const metadata = {
  title: "Cut Ludesc",
  description: "Generated by Aslam",
  icon: "/images/KensenLogoRound.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,500,0,0" />
      </head>
      <body className="min-h-screen p-0 m-0">
        <div className="min-h-screen bg-[#f7f7f7] flex flex-col">
          <Header/>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}